# Generated by Django 3.0.5 on 2020-05-25 18:10

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200524_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='https://www.youtube.com/watch?v=LAIVhl2CG8E')),
            ],
        ),
    ]
